class LanguageConstants {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'home': 'Home',
      'search': 'Search',
      'saved': 'Saved',
      'profile': 'Profile',
      'settings': 'Settings',
      'language': 'Language',
      'english': 'English',
      'vietnamese': 'Vietnamese',
      'notifications': 'Notifications',
      'job_alerts': 'Job Alerts',
      'profile_visibility': 'Profile Visibility',
      'edit_profile': 'Edit Profile',
      'featured_jobs': 'Featured Jobs',
      'search_jobs': 'Search Jobs',
      'saved_jobs': 'Saved Jobs',
      'personal_info': 'Personal Information',
      'professional_info': 'Professional Information',
      'preferences': 'Preferences',
      'email': 'Email',
      'phone': 'Phone',
      'location': 'Location',
      'experience': 'Experience',
      'education': 'Education',
      'languages': 'Languages',
      'public': 'Public',
      'private': 'Private',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
    },
    'vi': {
      'home': 'Trang chủ',
      'search': 'Tìm kiếm',
      'saved': 'Đã lưu',
      'profile': 'Hồ sơ',
      'settings': 'Cài đặt',
      'language': 'Ngôn ngữ',
      'english': 'Tiếng Anh',
      'vietnamese': 'Tiếng Việt',
      'notifications': 'Thông báo',
      'job_alerts': 'Thông báo việc làm',
      'profile_visibility': 'Hiển thị hồ sơ',
      'edit_profile': 'Chỉnh sửa hồ sơ',
      'featured_jobs': 'Việc làm nổi bật',
      'search_jobs': 'Tìm việc làm',
      'saved_jobs': 'Việc làm đã lưu',
      'personal_info': 'Thông tin cá nhân',
      'professional_info': 'Thông tin chuyên môn',
      'preferences': 'Tùy chọn',
      'email': 'Email',
      'phone': 'Điện thoại',
      'location': 'Địa điểm',
      'experience': 'Kinh nghiệm',
      'education': 'Học vấn',
      'languages': 'Ngôn ngữ',
      'public': 'Công khai',
      'private': 'Riêng tư',
      'enabled': 'Bật',
      'disabled': 'Tắt',
    },
  };

  static String getText(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? _localizedValues['en']![key]!;
  }
} 